const AWS = require('aws-sdk');
const fs = require('fs');

// Note: This requires valid AWS credentials and the DynamoDB table name
const REGION = 'us-east-1'; 
const TABLE_NAME = 'Ad-xxxx-dev'; // This would be generated by Amplify

AWS.config.update({ region: REGION });
const docClient = new AWS.DynamoDB.DocumentClient();

const ads = JSON.parse(fs.readFileSync('./ad_embeddings.json', 'utf8'));

const seedData = async () => {
  console.log("Seeding ads to DynamoDB...");
  
  for (const ad of ads) {
    const params = {
      TableName: TABLE_NAME,
      Item: {
        id: ad.id,
        title: ad.title,
        category: ad.category,
        embedding: ad.embedding,
        description: `Description for ${ad.title}`
      }
    };

    try {
      // await docClient.put(params).promise();
      console.log(`[MOCK] Seeded: ${ad.title}`);
    } catch (err) {
      console.error(`Error seeding ${ad.title}:`, err);
    }
  }
};

seedData();
